namespace HomeService.Contracts.CompanyPortal;

public sealed record CompanyPortalMissionResponse(
    Guid Id,
    string MissionNumber,
    string ServiceName,
    string CustomerName,
    string CustomerPhoneNumber,
    string Mode,
    string Status,
    string PaymentMethod,
    string PaymentStatus,
    DateTimeOffset? ScheduledFor,
    int EstimatedDurationMinutes,
    int? FinalTotalAmount,
    string Currency,
    Guid? ProviderId,
    string? ProviderName,
    int? CompanyQuotedAmount = null,
    string? CompanyQuoteJustification = null,
    DateTimeOffset? CompanyQuotedAt = null,
    DateTimeOffset? CustomerQuoteAcceptedAt = null,
    string? ServiceIconName = null,
    string? LocationLabel = null,
    int? ActualDurationMinutes = null,
    int? CustomerRating = null,
    string? CancellationReason = null,
    int PlatformCommissionAmount = 0,
    DateTimeOffset? CompanyAssignmentExpiresAt = null,
    decimal? ServiceLatitude = null,
    decimal? ServiceLongitude = null,
    string? CancellationActor = null,
    string? CancellationComment = null,
    int UnreadMessageCount = 0);
