namespace HomeService.Contracts.Companies;

public sealed record CompanyApplicationDetailResponse(
    Guid Id,
    Guid? CompanyId,
    string CompanyName,
    string? RegistrationNumber,
    string City,
    string? Address,
    string ContactName,
    string Email,
    string PhoneNumber,
    string? PlannedServices,
    int? EstimatedProviderCount,
    string Status,
    DateTimeOffset? SubmittedAt,
    DateTimeOffset? ReviewedAt,
    DateTimeOffset? LastReminderSentAt,
    DateTimeOffset? ActivationEmailSentAt,
    DateTimeOffset? ActivatedAt,
    string? CompanyAssignmentMode,
    string? LastActivationLink,
    DateTimeOffset? LastActivationLinkExpiresAt,
    string? ReviewNote,
    IReadOnlyList<CompanyApplicationDocumentResponse> Documents,
    IReadOnlyList<CompanyApplicationStatusHistoryResponse> StatusHistory);
