namespace HomeService.Contracts.Clients;

public sealed record ClientMissionListItemResponse(
    Guid MissionId,
    string MissionNumber,
    string Status,
    string QuoteStatus,
    string PaymentStatus,
    string? ServiceName,
    string? PrestationName,
    string? OptionName,
    string? ServiceAddress,
    DateTimeOffset CreatedAt,
    DateTimeOffset? ScheduledFor,
    int? Amount,
    string Currency,
    string PrimaryAction,
    Guid ServiceId,
    Guid? ServicePrestationId,
    Guid? ServiceOptionId,
    Guid? CompanyId,
    string? CompanyName,
    bool CanReorder,
    string? IconUrl = null,
    string? AssignedProviderName = null,
    string? AssignedProviderPhotoUrl = null);
